In [1]:
import numpy as np
import pandas as pd# import the dataset
df = pd.read_csv('/content/HepatitisCdata.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/HepatitisCdata.csv'

# **model implementation**

In [ ]:
df_getdummy=pd.get_dummies(data=df,columns=['Sex'])
X= df_getdummy.drop('Category',axis=1)
y= df_getdummy['Category']

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state =20)

NameError: name 'X' is not defined

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
# fit Logistic Regression to the training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

In [ ]:
from sklearn.metrics import accuracy_score
paccur=accuracy_score(y_true=y_train, y_pred=classifier.predict(X_train))
print('The accuracy of the logistic regression is: ' +str(paccur*100) + ' %.')


In [ ]:
cm = confusion_matrix(y_test,y_pred)
cm.shape

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 


In [ ]:
cm = confusion_matrix(y_test,y_pred)
cm_df = pd.DataFrame(cm,index=['0=Blood Donor','1=Hepatitis','2=Fibrosis','3=Cirrhosis'],
                               columns = ['0=Blood Donor','1=Hepatitis','2=Fibrosis','3=Cirrhosis'])
plt.figure(figsize=(15,4))
sns.heatmap(cm_df, annot=True)
plt.title=('Confusion matrix')
plt.ylabel=('Actual Values')
plt.xlabel=('Predicted Values')
plt.show()

# **Prediction**

In [ ]:
test_pred=classifier.predict([[37,55.5,0,6.6,30.0,23.2,7.8,7.1,1.2,89.0,29.5,9,87,34]])
test_pred

In [3]:
df.head()

NameError: name 'df' is not defined

# **Classification Model Implementation**

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
ds=pd.read_csv('/content/HepatitisCdata.csv')
ds.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/HepatitisCdata.csv'

In [ ]:
df_getdummy=pd.get_dummies(data=df, columns=['Sex'])
x = df_getdummy.drop('Category',axis=1)
y = df_getdummy['Category']


In [ ]:
y_test

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)


In [47]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


# **Logistic Regression**

In [48]:
 from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)
from sklearn.metrics import confusion_matrix
y_pred_log = lr.predict(x_test)
cm = confusion_matrix(y_test,y_pred_log)
print('confusion matrix:\n',cm)
from sklearn.metrics import accuracy_score
lra = accuracy_score(y_test,y_pred_log)
print('accuracy score = ',lra)


confusion matrix:
 [[99  0  0  0  0]
 [ 0  1  0  0  0]
 [ 4  0  0  3  1]
 [ 4  0  0  2  1]
 [ 1  0  0  0  7]]
accuracy score =  0.8861788617886179
