In [1]:
#access the userdefined module named as support.py
#importing the module as alias s
import support as s
s.printme("poojitha")

hello poojitha


In [2]:
import math

In [3]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [4]:
dir(s)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'printme']

In [5]:
#import function from module
from support import printme
printme("poojitha")

hello poojitha


In [11]:
help('modules')


Please wait a moment while I gather a list of all available modules...

Cython              codeop              more_itertools      sphinx
IPython             collections         mpmath              sphinxcontrib
OpenSSL             colorama            msgpack             sphinxify
PIL                 colorsys            msilib              sphinxthread
PyQt5               commctrl            msvcrt              spyder
TBB                 compileall          multipledispatch    spyder_kernels
__future__          comtypes            multiprocessing     sqlalchemy
_abc                concurrent          munkres             sqlite3
_aix_support        conda               mypy_extensions     sre_compile
_ast                conda_build         nacl                sre_constants
_asyncio            conda_content_trust navigator_updater   sre_parse
_bisect             conda_env           nbclassic           ssl
_black_version      conda_pack          nbclient            sspi
_blake2          

In [9]:
import math

In [10]:
dir(math)
printme(math.pi)

hello 3.141592653589793


In [14]:
import statistics as sts
sts.mean([2,4,6,8])

5

In [22]:
try:
    x=int(input("enter your iput"))
    
except ValueError:
        print("you gave a string try to give integer")

KeyboardInterrupt: Interrupted by user

In [26]:
try:
    x1="poojitha"
    print(x1)
   # f=open("demo.txt","r")
except NameError:
    print("your nameerror excepton has been handeled by except block")
except ValueError:
    print("your fileerror excepton has been handeled by except block")
except FileNotFound:
    print("your file excepton has been handeled by except block")
else:
    print("no exception")
finally:
    print("finally")




poojitha
no exception
finally


In [32]:
import numpy as np

In [33]:
print(numpy.__version__)

1.20.3


In [34]:
arr=numpy.array([1,2,3,4,5,6])
print(arr)

print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [35]:
arr=np.array((1,2,3,4,5,6))
print("1d array",arr)
#create 2-d array
arr1=np.array([[1,2,3],[4,5,6]])
print("2d array",arr1)

1d array [1 2 3 4 5 6]
2d array [[1 2 3]
 [4 5 6]]


In [36]:
#create 3-d array
arr3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [37]:
#dimensions checking of arrays
print("dim of arr",arr.ndim)
print("dim of arr1",arr1.ndim)
print("dim of arr3",arr3.ndim)

dim of arr 1
dim of arr1 2
dim of arr3 3


In [39]:
print(arr1[0][])

4


In [40]:
print(arr[)

IndexError: invalid index to scalar variable.

In [41]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [43]:
print(arr1[1,2])

6


In [44]:
print(arr3[0,1,2])

6


In [45]:
#negative indexing
print(arr1)

[[1 2 3]
 [4 5 6]]


In [47]:
print(arr1[1,-1])

6


In [59]:
#slicing
a=np.array([1,2,3,4,5,6,7])
print(a[1:4])
print(a[:4])
print(a[4:])
print(a[-3:-1])

[2 3 4]
[1 2 3 4]
[5 6 7]
[5 6]


In [60]:
#slicing in 2d
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b.ndim)
print(b)

2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [61]:
print(b[1,1:4])
print(b[1,2:4])
print(b[0:2,1])

[7 8 9]
[8 9]
[2 7]


In [62]:
#shape of the array
print("shape of array a:",a.shape)
print("shape of array b:",b.shape)

shape of array a: (7,)
shape of array b: (2, 5)


In [63]:
#iterate over array using loop
for x in b:
    print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [67]:
#scalar elements
for x in arr3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
1
2
3
4
5
6


In [68]:
#nd itter
for x in np.nditer(arr3):
    print(x)
for r in np.nditer(b):
    print(r)

1
2
3
4
5
6
1
2
3
4
5
6
1
2
3
4
5
6
7
8
9
10


In [69]:
#some trignometry functions
x=np.sin(np.pi/2)
print(x)

1.0


In [71]:
arr=np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/5])
z=np.sin(arr)
y=np.cos(arr)
print(z)
print(y)
#radian=pi/180*degree
arr=np.array([90,180,270,360])
x1=np.deg2rad(arr)
print(x1)

[1.         0.8660254  0.70710678 0.58778525]
[6.12323400e-17 5.00000000e-01 7.07106781e-01 8.09016994e-01]
[1.57079633 3.14159265 4.71238898 6.28318531]


In [72]:
arr1=np.array([np.pi/2,np.pi,1.5*np.pi,2*np.pi])
x=np.rad2deg(arr1)
print(x)

[ 90. 180. 270. 360.]


In [74]:

arr=np.around(3.145,2)
print(arr)

3.14


In [77]:
arr=np.floor([-3.166,3.667])
print(arr)

[-4.  3.]


In [ ]:
arr=np.cell([-3.166,3.667])
print(arr)

In [78]:
arr=np.trunc([-3.166,3.667])
print(arr)

[-3.  3.]


In [79]:
arr=np.fix([-3.166,3.667])
print(arr)

[-3.  3.]


In [80]:
#mathematical functions
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
addarray=np.add(arr1,arr2)
print(addarray)

[5 7 9]


In [84]:
sumarray=np.sum([arr1,arr2])
print(sumarray)

21


In [88]:
#you can sum along with axis
addarray=np.sum([arr1,arr2],axis=)
print(addarray)

[5 7 9]


In [89]:
a=np.array([1,2,3,4,5,6,7])
prodarray=np.prod(a)
print(prodarray)

5040


In [93]:
#create the prod over axix 
proarray=np.prod(b[0,0:,1,0:])
print(proarray)

IndexError: too many indices for array: array is 2-dimensional, but 4 were indexed

In [94]:
a=np.array([1,2,3,4,5,6,7])
prodovercolumn=np.prod([a],axis=0)
print(prodovercolumn)

[1 2 3 4 5 6 7]


In [95]:
a=np.array([1,2,3,4,5,6,7])
prodovercolumn=np.prod([a],axis=1)
print(prodovercolumn)

[5040]


In [96]:
#arthimetic operations
r1=np.array([10,11,12,13,14,15])
r2=np.array([20,21,22,23,24,25])
addarray=np.add(r1,r2)
print(addarray)

[30 32 34 36 38 40]


In [99]:

subarray=np.subtract(r2,r1)
print(subarray)
mulaarray=np.multiply(r1,r2)
print(addarray)

divarray=np.divide(r2,r1)
print(divarray)

[10 10 10 10 10 10]
[30 32 34 36 38 40]
[2.         1.90909091 1.83333333 1.76923077 1.71428571 1.66666667]


In [100]:
r1=np.array([1,2,3,4,5])
r2=np.array([1,2,3,4,5])
powa=np.power(r1,r2)
print(powa)

[   1    4   27  256 3125]


In [103]:
r1=np.array([1,-2,3,-4,5,6])
absA=np.absolute(r1)
print(absA)

[1 2 3 4 5 6]


In [102]:
r1=np.array([1,2,3,4,5])
r2=np.array([1,2,3,4,5])
divmodi=np.divmod(r1,r2)
print(divmodi)

(array([1, 1, 1, 1, 1], dtype=int32), array([0, 0, 0, 0, 0], dtype=int32))


In [ ]:
mean median mod varaince stddev
r1=np.array([1,2,3,4,5])
r2=np.array([1,2,3,4,5])

In [116]:
r1=np.array([1,2,3,4,5])
r2=np.array([85,45,37,87,54])
mean1=np.mean([r1,r2])
print(mean1)
mead1=np.median([r1,r2])
print(mead1)
mod1=np.mod(r2,r1)
print(mod1)
stddev1=np.std([r1,r2])
print(stddev1)


32.3
21.0
[0 1 1 3 4]
32.75072518281084
